name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          flake8 src/

      - name: Start MLflow server
        run: |
          nohup mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --host 0.0.0.0 \
            --port 5000 &
          sleep 10  # sleep time to start

      - name: Run tests
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          python -m pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/housing-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/housing-api:latest
